### ISSUE TITLE
SetSubMatrix problem

### ISSUE THREAD

**Issue by archiseb** [mathnet/mathnet-numerics#275] opened 2015-01-05 10:17 UTC
Hello 

I'm using Math.Net to perform FEM code, and i get some issuse in usage of SetSubMatrix in Matrix<double> objects.
I'm creating 6 Dense Matrices 6x6, and I'm composing from them 24x24 matrix. 
But, the end Matrix, after composing contains "holes" I've use DelimitedWriter.Write to export matrix to Excel and this is what I get...
![bez tytulu](https://cloud.githubusercontent.com/assets/9480668/5611800/82c011c4-94cb-11e4-81a5-d379ac636fea.jpg)

composing of 24x24 matrix part looks like this. All matrix K1,K2...K6 (which are 6x6)are fulfilled with doubles...

 //Composing Ke matrix
            // * Ke = {K1, K2, K3, K4
            //  *      K2T, K5, K6, K3T
            // *       K3T, K6, K5T, K2T
            // *       K4, K3, K2, K1T}
            //Row 0
            Ke.SetSubMatrix(0, 0, K1);
           Ke.SetSubMatrix(0, 6, K2);
           Ke.SetSubMatrix(0, 12, K3);
            Ke.SetSubMatrix(0, 18, K4);
            //Row 6
            Ke.SetSubMatrix(6, 0, K2.Transpose());
            Ke.SetSubMatrix(6, 6, K5);
            Ke.SetSubMatrix(6, 12, K6);
            Ke.SetSubMatrix(6, 18, K3.Transpose());
            ////Row 12
            Ke.SetSubMatrix(12, 0, K3.Transpose());
            Ke.SetSubMatrix(12, 6, K6);
            Ke.SetSubMatrix(12, 12, K5.Transpose());
            Ke.SetSubMatrix(12, 18, K2.Transpose());
            ////Row 18
            Ke.SetSubMatrix(18, 0, K4);
           Ke.SetSubMatrix(18, 6, K3);
            Ke.SetSubMatrix(18, 12, K2);
            Ke.SetSubMatrix(18, 18, K1.Transpose());
    
If I comment randomly any setsubmatrix from above, it gives different result....
As you see in excel, empty places are not even Zeros... that's really strange behaviour.
If you will need I can send you whole class.
Could you investigate what is wrong with this function....
Thank You

**Comment by cdrnet** [comment] 2015-01-05 17:50
Ugh, I'll have a look!

**Comment by cdrnet** [comment] 2015-01-05 18:43
Hm, I cannot reproduce so far. This is what I tried with Math.NET Numerics 3.4.0 in LinqPad (hence the `Dump` calls):

    var k = Matrix<double>.Build.Dense(6,6,(i,j) => 100.0 + 10.0*i+j);
    
    // simple way
    var m1 = Matrix<double>.Build.DenseOfMatrixArray(new[,]
        {{k,k*2,k*3,k*4},
        {k*5,k*6,k*7,k*8},
        {k*9,k*10,k*11,k*12},
        {k*13,k*14,k*15,k*16}});
    m1.ToArray().Dump();
    
    // doing it manually
    var m2 = Matrix<double>.Build.Dense(24,24);
    m2.SetSubMatrix(0,0,k);
    m2.SetSubMatrix(0,6,k*2);
    m2.SetSubMatrix(0,12,k*3);
    m2.SetSubMatrix(0,18,k*4);
    m2.SetSubMatrix(6,0,k*5);
    m2.SetSubMatrix(6,6,k*6);
    m2.SetSubMatrix(6,12,k*7);
    m2.SetSubMatrix(6,18,k*8);
    m2.SetSubMatrix(12,0,k*9);
    m2.SetSubMatrix(12,6,k*10);
    m2.SetSubMatrix(12,12,k*11);
    m2.SetSubMatrix(12,18,k*12);
    m2.SetSubMatrix(18,0,k*13);
    m2.SetSubMatrix(18,6,k*14);
    m2.SetSubMatrix(18,12,k*15);
    m2.SetSubMatrix(18,18,k*16);
    m2.ToArray().Dump();
    
    // difference is all 0
    (m1 - m2).ToArray().Dump();
    
    // verify DelimitedWriter can print it properly
    var writer = new StringWriter();
    DelimitedWriter.Write(writer,m1);
    writer.ToString().Dump();

What version of Math.NET Numerics are you using?

**Comment by cdrnet** [comment] 2015-01-09 10:19
Since dense matrices cannot technically have "no value" at some place this was more likely an issue outside of Math.NET Numerics (maybe an old version of the text data package?). I'm closing this, but please reopen if you can indeed reproduce with current versions.

**Closed by cdrnet** 2015-01-09 10:19 UTC
