### ISSUE TITLE
BfgsBMinimizer - ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by rostov-da** [mathnet/mathnet-numerics#510] opened 2017-08-29 14:30 UTC
Hello. There is a problem with the BfgsBMinimizer  (version 3.20.0.0)
ArgumentOutOfRangeException, 
File: QuadraticGradientProjectionSearch.cs,  
string number 86.

```
using System;
using MathNet.Numerics.LinearAlgebra;
using MathNet.Numerics.LinearAlgebra.Double;
using MathNet.Numerics.Optimization;
using MathNet.Numerics.Optimization.ObjectiveFunctions;

namespace TestInterface.MathLibTest
{
    public static class MathNetNumericsTest
    {
        public static void Make()
        {
            Func<Vector<double>, double> function = (Vector<double> vectorArg) =>
            {
                double x = vectorArg[0];
                double y = -1.0 * Math.Exp(- x * x);
                return y;
            };
            
            double gradientTolerance = 1e-10;
            double parameterTolerance = 1e-10;
            double functionProgressTolerance = 1e-10;
            int maxIterations = 1000;

            var initialGuess = new DenseVector(new[] { -1.0 });

            // Bad Bound
            var lowerBound = new DenseVector(new[] { -2.0 });
            var upperBound = new DenseVector(new[] { 2.0 });

            // Good Bound
            //var lowerBound = new DenseVector(new[] { -3.0 });
            //var upperBound = new DenseVector(new[] { 3.0 });

            var objective = ObjectiveFunction.Value(function);
            var objectiveWithGradient = new ForwardDifferenceGradientObjectiveFunction(objective, lowerBound, upperBound);
            var algorithm = new BfgsBMinimizer(gradientTolerance, parameterTolerance, functionProgressTolerance, maxIterations);
            var result = algorithm.FindMinimum(objectiveWithGradient, lowerBound, upperBound, initialGuess);

            var resultVector = result.MinimizingPoint;
            double xResult = resultVector[0];
        }
    }
 #}
```

  
#

**Comment by Shiney** [comment] 2021-08-02 11:45
Looks like the issue is that the loop on line 81 of QuadraticGradientProjectionSearch.cs, will never work if there is only one parameter, this can probably be fixed by making the check  for `jj + 1 >= orderedBreakpoint.Count - 1)` happen at the start of the loop instead

**Comment by Shiney** [comment] 2021-08-05 08:13
FYI Going to try to create a fix for this

**Comment by Shiney** [comment] 2021-08-20 07:57
Not really sure if I have linked this right to the PR but I've made a PR that fixes this here https://github.com/mathnet/mathnet-numerics/pull/858 #858

**Comment by cdrnet** [comment] 2021-08-22 11:03
Closing this as the PR has been merged. Thanks!

**Closed by cdrnet** 2021-08-22 11:03 UTC
Labels: needs investigation
