### ISSUE TITLE
LinearAlgebra.Matrix<double>.Multiply throws ArgumentException

### ISSUE THREAD

**Issue by IlmrynX** [mathnet/mathnet-numerics#358] opened 2015-12-24 03:29 UTC
Not sure if I should use a gist for this, but here's a screenshot, but the code below shows the same thing, yet my replacement works fine: http://prntscr.com/9hwy43

Both matrices are of size 3x1 but yet this code produces an exception.
```cs
var temp1 = -(Y - Forward());
var temp2 = Z3.Map(ActivatorPrime);
// Temporary replacement
var temp3 = new double[3,1];
for (int i = 0; i < 3; i++)
{
    temp3[i, 0] = temp1[i, 0] * temp2[i, 0];
}
D3 = Matrix<double>.Build.DenseOfArray(temp3);

// TODO: Checkout bug
D3 = temp1*temp2;  /// Exception thrown here
```
With the exception being:
```
ArgumentException was unhandled
An unhandled exception of type 'System.ArgumentException' occurred in MathNet.Numerics.dll

Additional information: Matrix dimensions must agree: op1 is 3x1, op2 is 3x1.
```

Thanks for any help!

**Comment by cdrnet** [comment] 2015-12-28 11:53
Given your temporary replacement, you seem to be looking for a pointwise product instead of a full matrix product. The following may help:

    D3 = temp1.PointwiseMultiply(temp2);

**Comment by cdrnet** [comment] 2015-12-28 11:57
Closing, but feel free to comment/reopen anyway if unclear.

**Closed by cdrnet** 2015-12-28 11:57 UTC

**Comment by RAACandeias** [comment] 2021-04-28 16:59
If the matrix with was "called" the multiply() was being multiplied with a scalar it would give error. "System.ArgumentOutOfRangeException: Matrix dimensions must agree: op1 is 3x3, op2 is 1x1." Why ??
I don't understand, is it not possible to multiply all the elements in a matrix with a scalar (single element)?

**Comment by cdrnet** [comment] 2021-04-29 09:47
Yes, it's certainly possible to multiply all elements in a matrix with a scalar. A 1x1 matrix is a matrix though, not a scalar.

**Comment by RAACandeias** [comment] 2021-04-29 10:58
The link you provided on "1" describes my situation the best. This is the line that is the issue:
"weights_hiddenXoutput = weights_hiddenXoutput.Add(C.Multiply(learningRate));"
learningRate is a double variable, so, a scalar. Multiply() as an overload that takes a double as input, essentially a scalar. C is a 3x3 matrix result of a previous multiplication. So why does the error say learningRate is a 1x1 matrix when it is not. I simply cannot understand what the issue is..
