### ISSUE TITLE
Fourier.Forward throws CUDA exception

### ISSUE THREAD

**Issue by Bovaz** [mathnet/mathnet-numerics#357] opened 2015-12-22 20:16 UTC
Upgrading to version 3.9, a call to Fourier.Forward like so:

    Fourier.Forward(B_E_SS, FourierOptions.Matlab);

(B_E_SS is a Complex[]) throws Exception:

    A first chance exception of type 'System.NotSupportedException' occurred in MathNet.Numerics.dll

    Additional information: Cuda Native Provider not found.

This was not the case with version 3.8, for the same code.

[EDIT]

If I click Continue on the popup for the Exception, I get another one of the same type, this time for 

    MKL Native Provider

Then if I click Continue again, I get the same Exception again, for:

     OpenBLAS Native Provider

If I click Continue one final time the program starts running and does not bother me anymore with exceptions.

Note that those exceptions are all raised even if I install the NuGet Packages for MKL.

Again, this did not happen to me with the same program, using MathNet.Numerics 3.8

**Comment by cdrnet** [comment] 2015-12-22 23:11
Do you just see them being thrown (e.g. if break on all exceptions is enabled when debugging) within Math.NET internal code, or do they reach your code? If they do, could you provide a call stack? Thanks.

**Comment by Bovaz** [comment] 2015-12-22 23:21
I see them being thrown the first time I make a call to Fourier.Forward. The IDE is set to break on all exceptions, so that is probably the reason why I see them at all. And indeed, if I run without debugger they do not pop up.

Anyway, Call stack (up until right before my function) (I am not sure how to format it properly):
 	MathNet.Numerics.dll!MathNet.Numerics.Providers.LinearAlgebra.OpenBlas.OpenBlasLinearAlgebraProvider.InitializeVerify()	Unknown
 	MathNet.Numerics.dll!MathNet.Numerics.Control.LinearAlgebraProvider.set(MathNet.Numerics.Providers.LinearAlgebra.ILinearAlgebraProvider value)	Unknown
 	MathNet.Numerics.dll!MathNet.Numerics.Control.UseNativeOpenBLAS()	Unknown
 	MathNet.Numerics.dll!MathNet.Numerics.Control.Try(System.Action action)	Unknown
 	MathNet.Numerics.dll!MathNet.Numerics.Control.TryUseNativeOpenBLAS()	Unknown
 	MathNet.Numerics.dll!MathNet.Numerics.Control.TryUseNative()	Unknown
 	MathNet.Numerics.dll!MathNet.Numerics.Control.ConfigureAuto()	Unknown
 	MathNet.Numerics.dll!MathNet.Numerics.Control.Control()	Unknown
 	[Native to Managed Transition]	
 	MathNet.Numerics.dll!MathNet.Numerics.Threading.CommonParallel.Invoke(System.Action[] actions)	Unknown
 	MathNet.Numerics.dll!MathNet.Numerics.IntegralTransforms.Fourier.BluesteinConvolutionParallel(System.Numerics.Complex[] samples)	Unknown
 	MathNet.Numerics.dll!MathNet.Numerics.IntegralTransforms.Fourier.Bluestein(System.Numerics.Complex[] samples, int exponentSign)	Unknown
 	MathNet.Numerics.dll!MathNet.Numerics.IntegralTransforms.Fourier.BluesteinForward(System.Numerics.Complex[] samples, MathNet.Numerics.IntegralTransforms.FourierOptions options)	Unknown
 	MathNet.Numerics.dll!MathNet.Numerics.IntegralTransforms.Fourier.Forward(System.Numerics.Complex[] samples, MathNet.Numerics.IntegralTransforms.FourierOptions options)	Unknown

**Comment by cdrnet** [comment] 2015-12-22 23:41
Thanks for the update. Yes, this is by design, and may happen at most once (per provider, hence the 3 exceptions) per process/AppDomain. It is not very elegant, but does it cause you any practical problems beyond the debugging annoyance?

**Comment by Bovaz** [comment] 2015-12-22 23:56
It is mostly annoying while debugging. 

The thing is, however, that those exceptions stay there even if I install the NuGet package for MKL. Specifically, the MKL related exception stays when I install the package with Id: 
    
    MathNet.Numerics.MKL.Win-x64


I cannot try the CUDA one because my computer does not have a nVidia graphic card.

**Comment by cdrnet** [comment] 2015-12-23 08:06
Can you verify that the two dll files of the MKL package did get copied to the x64 subfolder of your output folder, i.e. relative to your application binaries?

**Comment by cdrnet** [comment] 2016-02-13 18:47
Closing as this has been addressed in #374. Thanks for reporting!

**Closed by cdrnet** 2016-02-13 18:47 UTC
